'use strict';

exports.DFLAG_PUBLISHED = 0x01;
exports.DFLAG_ATOM_CACHE = 0x02;
exports.DFLAG_EXTENDED_REFERENCES = 0x04;
exports.DFLAG_DIST_MONITOR = 0x08;
exports.DFLAG_FUN_TAGS = 0x10;
exports.DFLAG_DIST_MONITOR_NAME = 0x20;
exports.DFLAG_HIDDEN_ATOM_CACHE = 0x40;
exports.DFLAG_NEW_FUN_TAGS = 0x80;
exports.DFLAG_EXTENDED_PIDS_PORTS = 0x100;
exports.DFLAG_EXPORT_PTR_TAG = 0x200;
exports.DFLAG_BIT_BINARIES = 0x400;
exports.DFLAG_NEW_FLOATS = 0x800;
exports.DFLAG_UNICODE_IO = 0x1000;
exports.DFLAG_DIST_HDR_ATOM_CACHE = 0x2000;
exports.DFLAG_SMALL_ATOM_TAGS = 0x4000;
exports.DFLAG_INTERNAL_TAGS = 0x8000;
exports.DFLAG_UTF8_ATOMS = 0x10000;
exports.DFLAG_MAP_TAG = 0x20000;
exports.DFLAG_BIG_CREATION = 0x40000;
exports.DFLAG_SEND_SENDER = 0x80000;
exports.DFLAG_BIG_SEQTRACE_LABELS = 0x100000;
exports.DFLAG_NO_MAGIC = 0x200000;
exports.DFLAG_EXIT_PAYLOAD = 0x400000;
exports.DFLAG_FRAGMENTS = 0x800000;
exports.DFLAG_HANDSHAKE_23 = 0x1000000;
exports.DFLAG_V4_NC = 0x400000000;
exports.DFLAG_ALIAS = 1 << 35;

const e = exports;
exports.DEFAULT_DFLAGS = (
  e.DFLAG_EXTENDED_REFERENCES
  | e.DFLAG_DIST_MONITOR
  | e.DFLAG_FUN_TAGS
  | e.DFLAG_DIST_MONITOR_NAME
  | e.DFLAG_NEW_FUN_TAGS
  | e.DFLAG_EXTENDED_PIDS_PORTS
  | e.DFLAG_EXPORT_PTR_TAG
  | e.DFLAG_BIT_BINARIES
  | e.DFLAG_NEW_FLOATS
  | e.DFLAG_SMALL_ATOM_TAGS
  | e.DFLAG_UTF8_ATOMS
  | e.DFLAG_MAP_TAG
  | e.DFLAG_BIG_CREATION
  | e.DFLAGS_SEND_SENDER
  | e.DFLAG_HANDSHAKE_23
  | e.DFLAG_V4_NC
  | e.DFLAG_ALIAS
);
